import type {
  EntityRecord,
  FeedItemRecord,
  SourceRecord,
  TagRecord,
  TagRuleRecord,
  WorkspaceRecord,
} from "@/lib/domain";

export const DEMO_WORKSPACE_ID = "ws_signal_deck";
export const DEMO_USER_ID = "usr_demo_operator";
export const DEMO_EMAIL = "demo@signaldeck.local";

export const defaultWorkspace: WorkspaceRecord = {
  id: DEMO_WORKSPACE_ID,
  name: "Signal Deck",
  slug: "signal-deck",
  description:
    "A decision-oriented watchfloor for AI UX/UI signals and logistics navigation competitors.",
};

export const seedTags: TagRecord[] = [
  { id: "tag_aiux", workspaceId: DEMO_WORKSPACE_ID, name: "AI UX/UI", slug: "ai-ux-ui", color: "#197d71", parentId: null, isActive: true },
  { id: "tag_truckerpath", workspaceId: DEMO_WORKSPACE_ID, name: "Trucker Path", slug: "trucker-path", color: "#b6542b", parentId: null, isActive: true },
  { id: "tag_ailoadboard", workspaceId: DEMO_WORKSPACE_ID, name: "AI Loadboard", slug: "ai-loadboard", color: "#975d00", parentId: null, isActive: true },
  { id: "tag_navpro", workspaceId: DEMO_WORKSPACE_ID, name: "NavPro", slug: "navpro", color: "#2c5c91", parentId: null, isActive: true },
  { id: "tag_competitor", workspaceId: DEMO_WORKSPACE_ID, name: "Competitor", slug: "competitor", color: "#6d4bcf", parentId: null, isActive: true },
  { id: "tag_feature", workspaceId: DEMO_WORKSPACE_ID, name: "Feature Launch", slug: "feature-launch", color: "#0e7a39", parentId: null, isActive: true },
  { id: "tag_pricing", workspaceId: DEMO_WORKSPACE_ID, name: "Pricing", slug: "pricing", color: "#905907", parentId: null, isActive: true },
  { id: "tag_partnership", workspaceId: DEMO_WORKSPACE_ID, name: "Partnership", slug: "partnership", color: "#6a687a", parentId: null, isActive: true },
  { id: "tag_navigation", workspaceId: DEMO_WORKSPACE_ID, name: "Navigation", slug: "navigation", color: "#206194", parentId: null, isActive: true },
  { id: "tag_loadboard", workspaceId: DEMO_WORKSPACE_ID, name: "Loadboard", slug: "loadboard", color: "#8c4b2a", parentId: null, isActive: true },
  { id: "tag_pattern", workspaceId: DEMO_WORKSPACE_ID, name: "Design Pattern", slug: "design-pattern", color: "#286a59", parentId: "tag_aiux", isActive: true },
];

export const seedEntities: EntityRecord[] = [
  {
    id: "entity_aiux",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "AI UX/UI Signals",
    slug: "ai-ux-ui-signals",
    kind: "topic",
    description: "Design systems, product interaction patterns, and AI-native workflows.",
    color: "#197d71",
  },
  {
    id: "entity_truckerpath",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "Trucker Path",
    slug: "trucker-path",
    kind: "competitor",
    description: "Freight planning, route discovery, and driver tooling signals.",
    color: "#b6542b",
  },
  {
    id: "entity_ailoadboard",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "AI Loadboard",
    slug: "ai-loadboard",
    kind: "competitor",
    description: "Marketplace, pricing and matching strategy movements.",
    color: "#975d00",
  },
  {
    id: "entity_navpro",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "NavPro Web",
    slug: "navpro-web",
    kind: "product",
    description: "Navigation and trip-planning web experience benchmark set.",
    color: "#2c5c91",
  },
];

export const seedSources: SourceRecord[] = [
  {
    id: "source_nn_group",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    name: "NN/g",
    slug: "nn-group",
    type: "website",
    url: "https://www.nngroup.com/articles/",
    refreshMinutes: 30,
    priority: 90,
    isActive: true,
    healthStatus: "healthy",
    config: { listSelector: "article", itemType: "article" },
    defaultTagIds: ["tag_aiux", "tag_pattern"],
    lastFetchedAt: new Date("2026-03-06T08:00:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_lenny",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    name: "Lenny's Newsletter Podcast",
    slug: "lennys-podcast",
    type: "youtube",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC4Jo7vE3dAn8tJz2PUQfIig",
    refreshMinutes: 30,
    priority: 82,
    isActive: true,
    healthStatus: "healthy",
    config: { feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UC4Jo7vE3dAn8tJz2PUQfIig", itemType: "video" },
    defaultTagIds: ["tag_aiux"],
    lastFetchedAt: new Date("2026-03-06T08:15:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_truckerpath_blog",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_truckerpath",
    name: "Trucker Path Blog",
    slug: "trucker-path-blog",
    type: "website",
    url: "https://truckerpath.com/blog/",
    refreshMinutes: 60,
    priority: 95,
    isActive: true,
    healthStatus: "healthy",
    config: { listSelector: ".post", itemType: "update" },
    defaultTagIds: ["tag_truckerpath", "tag_competitor"],
    lastFetchedAt: new Date("2026-03-06T08:22:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_ailoadboard_x",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_ailoadboard",
    name: "AI Loadboard X",
    slug: "ai-loadboard-x",
    type: "x",
    url: "https://x.com/AILoadboard",
    refreshMinutes: 30,
    priority: 92,
    isActive: true,
    healthStatus: "degraded",
    config: { handle: "AILoadboard", rssUrl: "https://rsshub.app/x/user/AILoadboard", itemType: "post" },
    defaultTagIds: ["tag_ailoadboard", "tag_competitor", "tag_loadboard"],
    lastFetchedAt: new Date("2026-03-06T07:40:00.000Z"),
    lastErrorMessage: "Using fallback adapter. Official feed unavailable.",
  },
  {
    id: "source_navpro_updates",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_navpro",
    name: "NavPro Release Notes",
    slug: "navpro-release-notes",
    type: "rss",
    url: "https://example.com/navpro/releases.xml",
    refreshMinutes: 30,
    priority: 88,
    isActive: true,
    healthStatus: "healthy",
    config: { itemType: "update" },
    defaultTagIds: ["tag_navpro", "tag_navigation"],
    lastFetchedAt: new Date("2026-03-06T08:05:00.000Z"),
    lastErrorMessage: null,
  },
];

export const seedRules: TagRuleRecord[] = [
  {
    id: "rule_pricing",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "Pricing motion",
    isActive: true,
    priority: 100,
    sourceId: null,
    conditions: { keywords: ["pricing", "plan", "subscription"] },
    actions: { tagIds: ["tag_pricing"] },
  },
  {
    id: "rule_partnerships",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "Partnership detection",
    isActive: true,
    priority: 90,
    sourceId: null,
    conditions: { keywords: ["partner", "integration", "alliance"] },
    actions: { tagIds: ["tag_partnership"] },
  },
  {
    id: "rule_navigation",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "Navigation topic",
    isActive: true,
    priority: 80,
    sourceId: null,
    conditions: { keywords: ["routing", "navigation", "trip planning"] },
    actions: { tagIds: ["tag_navigation"] },
  },
];

export const seedFeedItems: FeedItemRecord[] = [
  {
    id: "item_ai_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    primarySourceId: "source_nn_group",
    sourceIds: ["source_nn_group"],
    title: "Designing for AI confidence: how to show uncertainty without losing trust",
    excerpt: "A practical look at confidence cues, escalation states, and how to keep users oriented when AI output quality varies.",
    canonicalUrl: "https://www.nngroup.com/articles/ai-confidence-patterns",
    contentType: "article",
    publishedAt: new Date("2026-03-06T06:00:00.000Z"),
    ingestedAt: new Date("2026-03-06T08:00:00.000Z"),
    fingerprint: "fp_ai_1",
    authorName: "NN/g",
    thumbnailUrl: null,
    tagIds: ["tag_aiux", "tag_pattern"],
  },
  {
    id: "item_ai_2",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    primarySourceId: "source_lenny",
    sourceIds: ["source_lenny"],
    title: "AI-first onboarding: teaching power users without slowing the first session",
    excerpt: "Notes from a product interview on progressive disclosure, agent handoff and high-signal starter workflows.",
    canonicalUrl: "https://youtube.com/watch?v=signal-ai-onboarding",
    contentType: "video",
    publishedAt: new Date("2026-03-05T17:30:00.000Z"),
    ingestedAt: new Date("2026-03-06T08:15:00.000Z"),
    fingerprint: "fp_ai_2",
    authorName: "Lenny's Podcast",
    thumbnailUrl: null,
    tagIds: ["tag_aiux"],
  },
  {
    id: "item_tp_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_truckerpath",
    primarySourceId: "source_truckerpath_blog",
    sourceIds: ["source_truckerpath_blog"],
    title: "Trucker Path refreshes route planning dashboard for fleet dispatchers",
    excerpt: "A product update focused on route context panels, lane filters and more visible stop intelligence.",
    canonicalUrl: "https://truckerpath.com/blog/route-planning-dashboard-refresh",
    contentType: "update",
    publishedAt: new Date("2026-03-06T04:45:00.000Z"),
    ingestedAt: new Date("2026-03-06T08:22:00.000Z"),
    fingerprint: "fp_tp_1",
    authorName: "Trucker Path",
    thumbnailUrl: null,
    tagIds: ["tag_truckerpath", "tag_competitor", "tag_navigation", "tag_feature"],
  },
  {
    id: "item_tp_2",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_truckerpath",
    primarySourceId: "source_truckerpath_blog",
    sourceIds: ["source_truckerpath_blog"],
    title: "Trucker Path announces partner network expansion for fuel savings",
    excerpt: "The move signals a broader platform story around trip planning, partnerships and lane economics.",
    canonicalUrl: "https://truckerpath.com/blog/fuel-partner-network-expansion",
    contentType: "article",
    publishedAt: new Date("2026-03-05T11:00:00.000Z"),
    ingestedAt: new Date("2026-03-06T08:22:00.000Z"),
    fingerprint: "fp_tp_2",
    authorName: "Trucker Path",
    thumbnailUrl: null,
    tagIds: ["tag_truckerpath", "tag_competitor", "tag_partnership"],
  },
  {
    id: "item_al_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_ailoadboard",
    primarySourceId: "source_ailoadboard_x",
    sourceIds: ["source_ailoadboard_x"],
    title: "AI Loadboard teases dynamic lane pricing controls on X",
    excerpt: "The post hints at broker-facing pricing levers and faster feedback loops in the loadboard workflow.",
    canonicalUrl: "https://x.com/AILoadboard/status/1001",
    contentType: "post",
    publishedAt: new Date("2026-03-06T02:40:00.000Z"),
    ingestedAt: new Date("2026-03-06T07:40:00.000Z"),
    fingerprint: "fp_al_1",
    authorName: "AI Loadboard",
    thumbnailUrl: null,
    tagIds: ["tag_ailoadboard", "tag_competitor", "tag_loadboard", "tag_pricing"],
  },
  {
    id: "item_nav_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_navpro",
    primarySourceId: "source_navpro_updates",
    sourceIds: ["source_navpro_updates"],
    title: "NavPro web adds map-side trip edit drawer with persistent route context",
    excerpt: "A web release aimed at reducing full-page jumps when refining a route mid-planning session.",
    canonicalUrl: "https://example.com/navpro/release/trip-edit-drawer",
    contentType: "update",
    publishedAt: new Date("2026-03-06T01:00:00.000Z"),
    ingestedAt: new Date("2026-03-06T08:05:00.000Z"),
    fingerprint: "fp_nav_1",
    authorName: "NavPro",
    thumbnailUrl: null,
    tagIds: ["tag_navpro", "tag_navigation", "tag_feature"],
  },
  {
    id: "item_industry_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: null,
    primarySourceId: "source_ailoadboard_x",
    sourceIds: ["source_ailoadboard_x"],
    title: "Loadboard operators are shifting pricing communication into live surfaces",
    excerpt: "Across web apps and social previews, pricing updates are moving closer to dispatch workflows rather than buried in docs.",
    canonicalUrl: "https://x.com/AILoadboard/status/1002",
    contentType: "post",
    publishedAt: new Date("2026-03-04T20:20:00.000Z"),
    ingestedAt: new Date("2026-03-06T07:40:00.000Z"),
    fingerprint: "fp_industry_1",
    authorName: "AI Loadboard",
    thumbnailUrl: null,
    tagIds: ["tag_loadboard", "tag_pricing"],
  },
];
