import type {
  CategoryRecord,
  EntityRecord,
  FeedItemRecord,
  SourceRecord,
  TagRecord,
  TagRuleRecord,
  WorkspaceRecord,
} from "@/lib/domain";

export const DEMO_WORKSPACE_ID = "ws_signal_deck";
export const DEMO_USER_ID = "usr_demo_operator";
export const DEMO_EMAIL = "demo@signaldeck.local";

export const defaultWorkspace: WorkspaceRecord = {
  id: DEMO_WORKSPACE_ID,
  name: "Signal Deck",
  slug: "signal-deck",
  description:
    "A decision-oriented watchfloor for AI UX/UI signals and logistics navigation competitors.",
};

export const seedTags: TagRecord[] = [
  { id: "tag_aiux", workspaceId: DEMO_WORKSPACE_ID, name: "AI UX/UI", slug: "ai-ux-ui", color: "#197d71", parentId: null, isActive: true },
  {
    id: "tag_website_inspiration",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "Website Inspiration",
    slug: "website-inspiration",
    color: "#7c5c2b",
    parentId: null,
    isActive: true,
  },
  { id: "tag_truckerpath", workspaceId: DEMO_WORKSPACE_ID, name: "Trucker Path", slug: "trucker-path", color: "#b6542b", parentId: null, isActive: true },
  { id: "tag_ailoadboard", workspaceId: DEMO_WORKSPACE_ID, name: "AI Loadboard", slug: "ai-loadboard", color: "#975d00", parentId: null, isActive: true },
  { id: "tag_navpro", workspaceId: DEMO_WORKSPACE_ID, name: "NavPro", slug: "navpro", color: "#2c5c91", parentId: null, isActive: true },
  { id: "tag_competitor", workspaceId: DEMO_WORKSPACE_ID, name: "Competitor", slug: "competitor", color: "#6d4bcf", parentId: null, isActive: true },
  { id: "tag_feature", workspaceId: DEMO_WORKSPACE_ID, name: "Feature Launch", slug: "feature-launch", color: "#0e7a39", parentId: null, isActive: true },
  { id: "tag_pricing", workspaceId: DEMO_WORKSPACE_ID, name: "Pricing", slug: "pricing", color: "#905907", parentId: null, isActive: true },
  { id: "tag_partnership", workspaceId: DEMO_WORKSPACE_ID, name: "Partnership", slug: "partnership", color: "#6a687a", parentId: null, isActive: true },
  { id: "tag_navigation", workspaceId: DEMO_WORKSPACE_ID, name: "Navigation", slug: "navigation", color: "#206194", parentId: null, isActive: true },
  { id: "tag_loadboard", workspaceId: DEMO_WORKSPACE_ID, name: "Loadboard", slug: "loadboard", color: "#8c4b2a", parentId: null, isActive: true },
  { id: "tag_pattern", workspaceId: DEMO_WORKSPACE_ID, name: "Design Pattern", slug: "design-pattern", color: "#286a59", parentId: "tag_aiux", isActive: true },
];

export const seedEntities: EntityRecord[] = [
  {
    id: "entity_aiux",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "AI UX/UI Signals",
    slug: "ai-ux-ui-signals",
    kind: "topic",
    description: "Design systems, product interaction patterns, and AI-native workflows.",
    color: "#197d71",
  },
  {
    id: "entity_truckerpath",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "Trucker Path",
    slug: "trucker-path",
    kind: "competitor",
    description: "Freight planning, route discovery, and driver tooling signals.",
    color: "#b6542b",
  },
  {
    id: "entity_ailoadboard",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "AI Loadboard",
    slug: "ai-loadboard",
    kind: "competitor",
    description: "Marketplace, pricing and matching strategy movements.",
    color: "#975d00",
  },
  {
    id: "entity_navpro",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "NavPro Web",
    slug: "navpro-web",
    kind: "product",
    description: "Navigation and trip-planning web experience benchmark set.",
    color: "#2c5c91",
  },
];

export const seedCategories: CategoryRecord[] = [
  {
    id: "category_aiux",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "AI UX/UI",
    slug: "ai-ux-ui",
    description: "Interaction patterns, onboarding models, trust cues and AI-native workflows.",
    tone: "sand",
    position: 10,
    isActive: true,
    tagIds: ["tag_aiux"],
    entityIds: [],
    entityKinds: [],
  },
  {
    id: "category_website_inspiration",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "Website Inspiration",
    slug: "website-inspiration",
    description: "Fresh gallery drops, standout landing pages and review-worthy inspiration.",
    tone: "sand",
    position: 20,
    isActive: true,
    tagIds: ["tag_website_inspiration"],
    entityIds: [],
    entityKinds: [],
  },
  {
    id: "category_competitor_watch",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "Competitor Watch",
    slug: "competitor-watch",
    description: "Signals across Trucker Path, AI Loadboard, NavPro and adjacent movers.",
    tone: "amber",
    position: 30,
    isActive: true,
    tagIds: [],
    entityIds: [],
    entityKinds: ["competitor"],
  },
  {
    id: "category_industry_signals",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "Industry Signals",
    slug: "industry-signals",
    description: "Navigation, pricing, routing and loadboard signals across the category.",
    tone: "ink",
    position: 40,
    isActive: true,
    tagIds: ["tag_navigation", "tag_loadboard", "tag_pricing"],
    entityIds: [],
    entityKinds: [],
  },
];

export const seedSources: SourceRecord[] = [
  {
    id: "source_nn_group",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    name: "NN/g",
    slug: "nn-group",
    type: "website",
    url: "https://www.nngroup.com/articles/",
    refreshMinutes: 30,
    priority: 90,
    isActive: true,
    healthStatus: "healthy",
    config: { listSelector: "article", itemType: "article" },
    defaultTagIds: ["tag_aiux", "tag_pattern"],
    lastFetchedAt: new Date("2026-03-06T08:00:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_lenny",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    name: "Lenny's Newsletter Podcast",
    slug: "lennys-podcast",
    type: "youtube",
    url: "https://www.youtube.com/channel/UC4Jo7vE3dAn8tJz2PUQfIig",
    refreshMinutes: 30,
    priority: 82,
    isActive: true,
    healthStatus: "healthy",
    config: {
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UC4Jo7vE3dAn8tJz2PUQfIig",
      channelId: "UC4Jo7vE3dAn8tJz2PUQfIig",
      channelUrl: "https://www.youtube.com/channel/UC4Jo7vE3dAn8tJz2PUQfIig",
      inputUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UC4Jo7vE3dAn8tJz2PUQfIig",
      itemType: "video",
    },
    defaultTagIds: ["tag_aiux"],
    lastFetchedAt: new Date("2026-03-06T08:15:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_openai_youtube",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    name: "OpenAI YouTube",
    slug: "openai-youtube",
    type: "youtube",
    url: "https://www.youtube.com/@OpenAI",
    refreshMinutes: 30,
    priority: 98,
    isActive: true,
    healthStatus: "healthy",
    config: {
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCXZCJLdBC09xxGZ6gcdrc6A",
      channelId: "UCXZCJLdBC09xxGZ6gcdrc6A",
      channelUrl: "https://www.youtube.com/channel/UCXZCJLdBC09xxGZ6gcdrc6A",
      handleUrl: "https://www.youtube.com/@OpenAI",
      inputUrl: "https://www.youtube.com/@OpenAI",
      itemType: "video",
    },
    defaultTagIds: ["tag_aiux", "tag_feature"],
    lastFetchedAt: new Date("2026-03-07T09:00:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_yc_youtube",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    name: "Y Combinator YouTube",
    slug: "y-combinator-youtube",
    type: "youtube",
    url: "https://www.youtube.com/@ycombinator",
    refreshMinutes: 30,
    priority: 84,
    isActive: true,
    healthStatus: "healthy",
    config: {
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCcefcZRL2oaA_uBNeo5UOWg",
      channelId: "UCcefcZRL2oaA_uBNeo5UOWg",
      channelUrl: "https://www.youtube.com/channel/UCcefcZRL2oaA_uBNeo5UOWg",
      handleUrl: "https://www.youtube.com/@ycombinator",
      inputUrl: "https://www.youtube.com/@ycombinator",
      itemType: "video",
    },
    defaultTagIds: ["tag_aiux", "tag_pattern"],
    lastFetchedAt: new Date("2026-03-07T13:00:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_diveclub_youtube",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    name: "Dive Club YouTube",
    slug: "dive-club-youtube",
    type: "youtube",
    url: "https://www.youtube.com/@joindiveclub",
    refreshMinutes: 30,
    priority: 83,
    isActive: true,
    healthStatus: "healthy",
    config: {
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCkCnraWwlnBw1_i7C9-3p0w",
      channelId: "UCkCnraWwlnBw1_i7C9-3p0w",
      channelUrl: "https://www.youtube.com/channel/UCkCnraWwlnBw1_i7C9-3p0w",
      handleUrl: "https://www.youtube.com/@joindiveclub",
      inputUrl: "https://www.youtube.com/@joindiveclub",
      itemType: "video",
    },
    defaultTagIds: ["tag_aiux", "tag_pattern"],
    lastFetchedAt: new Date("2026-03-07T13:00:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_framer_youtube",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    name: "Framer YouTube",
    slug: "framer-youtube",
    type: "youtube",
    url: "https://www.youtube.com/@Framer",
    refreshMinutes: 30,
    priority: 88,
    isActive: true,
    healthStatus: "healthy",
    config: {
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCW5gUZ7lKGrAbLOkHv2xfbw",
      channelId: "UCW5gUZ7lKGrAbLOkHv2xfbw",
      channelUrl: "https://www.youtube.com/channel/UCW5gUZ7lKGrAbLOkHv2xfbw",
      handleUrl: "https://www.youtube.com/@Framer",
      inputUrl: "https://www.youtube.com/@Framer",
      itemType: "video",
    },
    defaultTagIds: ["tag_aiux", "tag_feature", "tag_pattern"],
    lastFetchedAt: new Date("2026-03-07T13:00:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_alanchen_youtube",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    name: "Alan Chen YouTube",
    slug: "alan-chen-youtube",
    type: "youtube",
    url: "https://www.youtube.com/@AlanChen",
    refreshMinutes: 30,
    priority: 76,
    isActive: true,
    healthStatus: "healthy",
    config: {
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCaIIFXfdQUYf3OHPIFNDdrQ",
      channelId: "UCaIIFXfdQUYf3OHPIFNDdrQ",
      channelUrl: "https://www.youtube.com/channel/UCaIIFXfdQUYf3OHPIFNDdrQ",
      handleUrl: "https://www.youtube.com/@AlanChen",
      inputUrl: "https://www.youtube.com/@AlanChen",
      itemType: "video",
    },
    defaultTagIds: ["tag_aiux"],
    lastFetchedAt: new Date("2026-03-07T13:00:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_skateiq_youtube",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: null,
    name: "SkateIQ YouTube",
    slug: "skateiq-youtube",
    type: "youtube",
    url: "https://www.youtube.com/@Skateiq",
    refreshMinutes: 30,
    priority: 58,
    isActive: true,
    healthStatus: "healthy",
    config: {
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UC-Pk-TTaSrDOjkPKQ7C8HXQ",
      channelId: "UC-Pk-TTaSrDOjkPKQ7C8HXQ",
      channelUrl: "https://www.youtube.com/channel/UC-Pk-TTaSrDOjkPKQ7C8HXQ",
      handleUrl: "https://www.youtube.com/@Skateiq",
      inputUrl: "https://www.youtube.com/@Skateiq",
      itemType: "video",
    },
    defaultTagIds: [],
    lastFetchedAt: new Date("2026-03-07T13:00:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_openai_x",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    name: "OpenAI X",
    slug: "openai-x",
    type: "x",
    url: "https://x.com/OpenAI",
    refreshMinutes: 30,
    priority: 89,
    isActive: true,
    healthStatus: "degraded",
    config: {
      handle: "OpenAI",
      rssUrl: "https://nitter.net/OpenAI/rss",
      itemType: "post",
      avatarUrl: "https://pbs.twimg.com/profile_images/1885410181409820672/ztsaR0JW.jpg",
    },
    defaultTagIds: ["tag_aiux"],
    lastFetchedAt: null,
    lastErrorMessage: "Public X bridge is configured but not currently returning readable feed items.",
  },
  {
    id: "source_vercel_x",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: null,
    name: "Vercel X",
    slug: "vercel-x",
    type: "x",
    url: "https://x.com/vercel",
    refreshMinutes: 30,
    priority: 78,
    isActive: true,
    healthStatus: "degraded",
    config: {
      handle: "vercel",
      rssUrl: "https://nitter.net/vercel/rss",
      itemType: "post",
      avatarUrl: "https://pbs.twimg.com/profile_images/1767351110228918272/3Pndc5OT.png",
    },
    defaultTagIds: ["tag_feature"],
    lastFetchedAt: null,
    lastErrorMessage: "Public X bridge is configured but not currently returning readable feed items.",
  },
  {
    id: "source_linear_x",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: null,
    name: "Linear X",
    slug: "linear-x",
    type: "x",
    url: "https://x.com/linear",
    refreshMinutes: 30,
    priority: 74,
    isActive: true,
    healthStatus: "degraded",
    config: {
      handle: "linear",
      rssUrl: "https://nitter.net/linear/rss",
      itemType: "post",
      avatarUrl: "https://pbs.twimg.com/profile_images/1882353118530224128/l8meBvMg.jpg",
    },
    defaultTagIds: ["tag_feature"],
    lastFetchedAt: null,
    lastErrorMessage: "Public X bridge is configured but not currently returning readable feed items.",
  },
  {
    id: "source_andy_hooke_x",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    name: "Andy Hooke X",
    slug: "andy-hooke-x",
    type: "x",
    url: "https://x.com/andy_hooke",
    refreshMinutes: 30,
    priority: 96,
    isActive: true,
    healthStatus: "healthy",
    config: {
      handle: "andy_hooke",
      rssUrl: "https://nitter.net/andy_hooke/rss",
      itemType: "post",
      liveDemo: true,
      avatarUrl: "https://pbs.twimg.com/profile_images/1546442126543785984/rPOmKAIB.jpg",
    },
    defaultTagIds: ["tag_aiux", "tag_pattern"],
    lastFetchedAt: new Date("2026-03-09T15:20:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_truckerpath_blog",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_truckerpath",
    name: "Trucker Path Blog",
    slug: "trucker-path-blog",
    type: "website",
    url: "https://truckerpath.com/blog/",
    refreshMinutes: 60,
    priority: 95,
    isActive: true,
    healthStatus: "healthy",
    config: { listSelector: ".post", itemType: "update" },
    defaultTagIds: ["tag_truckerpath", "tag_competitor"],
    lastFetchedAt: new Date("2026-03-06T08:22:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_ailoadboard_x",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_ailoadboard",
    name: "AI Loadboard X",
    slug: "ai-loadboard-x",
    type: "x",
    url: "https://x.com/AILoadboard",
    refreshMinutes: 30,
    priority: 92,
    isActive: true,
    healthStatus: "degraded",
    config: {
      handle: "AILoadboard",
      rssUrl: "https://rsshub.app/x/user/AILoadboard",
      itemType: "post",
      avatarUrl: "https://pbs.twimg.com/profile_images/2008546467615580160/57KcqsTA.jpg",
    },
    defaultTagIds: ["tag_ailoadboard", "tag_competitor", "tag_loadboard"],
    lastFetchedAt: new Date("2026-03-06T07:40:00.000Z"),
    lastErrorMessage: "Using fallback adapter. Official feed unavailable.",
  },
  {
    id: "source_navpro_updates",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_navpro",
    name: "NavPro Release Notes",
    slug: "navpro-release-notes",
    type: "rss",
    url: "https://example.com/navpro/releases.xml",
    refreshMinutes: 30,
    priority: 88,
    isActive: true,
    healthStatus: "healthy",
    config: { itemType: "update" },
    defaultTagIds: ["tag_navpro", "tag_navigation"],
    lastFetchedAt: new Date("2026-03-06T08:05:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_saaslandingpage_gallery",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: null,
    name: "SaaS Landing Page",
    slug: "saas-landing-page",
    type: "rss",
    url: "https://saaslandingpage.com/feed/",
    refreshMinutes: 60,
    priority: 86,
    isActive: true,
    healthStatus: "healthy",
    config: {
      extractorProfile: "gallery-rss",
      itemType: "article",
    },
    defaultTagIds: ["tag_website_inspiration"],
    lastFetchedAt: new Date("2026-03-10T12:00:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_onepagelove_gallery",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: null,
    name: "One Page Love",
    slug: "one-page-love",
    type: "rss",
    url: "https://onepagelove.com/feed",
    refreshMinutes: 60,
    priority: 84,
    isActive: true,
    healthStatus: "healthy",
    config: {
      extractorProfile: "gallery-rss",
      itemType: "article",
    },
    defaultTagIds: ["tag_website_inspiration"],
    lastFetchedAt: new Date("2026-03-10T14:46:00.000Z"),
    lastErrorMessage: null,
  },
  {
    id: "source_a1_gallery",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: null,
    name: "A1 Gallery",
    slug: "a1-gallery",
    type: "website",
    url: "https://www.a1.gallery/",
    refreshMinutes: 60,
    priority: 82,
    isActive: true,
    healthStatus: "healthy",
    config: {
      extractorProfile: "a1-gallery-home",
      itemType: "article",
    },
    defaultTagIds: ["tag_website_inspiration"],
    lastFetchedAt: new Date("2026-03-10T12:30:00.000Z"),
    lastErrorMessage: null,
  },
];

export const seedRules: TagRuleRecord[] = [
  {
    id: "rule_pricing",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "Pricing motion",
    isActive: true,
    priority: 100,
    sourceId: null,
    conditions: { keywords: ["pricing", "plan", "subscription"] },
    actions: { tagIds: ["tag_pricing"] },
  },
  {
    id: "rule_partnerships",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "Partnership detection",
    isActive: true,
    priority: 90,
    sourceId: null,
    conditions: { keywords: ["partner", "integration", "alliance"] },
    actions: { tagIds: ["tag_partnership"] },
  },
  {
    id: "rule_navigation",
    workspaceId: DEMO_WORKSPACE_ID,
    name: "Navigation topic",
    isActive: true,
    priority: 80,
    sourceId: null,
    conditions: { keywords: ["routing", "navigation", "trip planning"] },
    actions: { tagIds: ["tag_navigation"] },
  },
];

export const seedFeedItems: FeedItemRecord[] = [
  {
    id: "item_openai_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    primarySourceId: "source_openai_youtube",
    sourceIds: ["source_openai_youtube"],
    title: "The Codex app is now on Windows",
    excerpt:
      "OpenAI shipped the Windows version of Codex with a native sandbox and stronger PowerShell-oriented developer workflows.",
    canonicalUrl: "https://www.youtube.com/watch?v=8hNcRChDrNk",
    contentType: "video",
    publishedAt: new Date("2026-03-05T20:55:53.000Z"),
    ingestedAt: new Date("2026-03-07T09:00:00.000Z"),
    fingerprint: "fp_openai_1",
    authorName: "OpenAI",
    thumbnailUrl: "https://i.ytimg.com/vi/8hNcRChDrNk/hqdefault.jpg",
    mediaLabel: "01:12",
    tagIds: ["tag_aiux", "tag_feature"],
  },
  {
    id: "item_openai_2",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    primarySourceId: "source_openai_youtube",
    sourceIds: ["source_openai_youtube"],
    title: "Interrupting and Adding Details in GPT-5.4 Thinking",
    excerpt:
      "A walkthrough of plan-first reasoning where the user can interrupt, refine direction, and steer the final output mid-thought.",
    canonicalUrl: "https://www.youtube.com/watch?v=qSHMlduU6Lw",
    contentType: "video",
    publishedAt: new Date("2026-03-05T18:20:32.000Z"),
    ingestedAt: new Date("2026-03-07T09:00:00.000Z"),
    fingerprint: "fp_openai_2",
    authorName: "OpenAI",
    thumbnailUrl: "https://i.ytimg.com/vi/qSHMlduU6Lw/hqdefault.jpg",
    mediaLabel: "04:18",
    tagIds: ["tag_aiux", "tag_pattern", "tag_feature"],
  },
  {
    id: "item_openai_3",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    primarySourceId: "source_openai_youtube",
    sourceIds: ["source_openai_youtube"],
    title: "Computer Use & Frontend UI with GPT-5.4 Thinking",
    excerpt:
      "A product-focused demo of stronger computer-use and frontend reasoning, including lower token usage and more persistent execution.",
    canonicalUrl: "https://www.youtube.com/watch?v=YICiHiU2GBU",
    contentType: "video",
    publishedAt: new Date("2026-03-05T18:18:38.000Z"),
    ingestedAt: new Date("2026-03-07T09:00:00.000Z"),
    fingerprint: "fp_openai_3",
    authorName: "OpenAI",
    thumbnailUrl: "https://i.ytimg.com/vi/YICiHiU2GBU/hqdefault.jpg",
    mediaLabel: "05:07",
    tagIds: ["tag_aiux", "tag_pattern", "tag_feature"],
  },
  {
    id: "item_yc_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    primarySourceId: "source_yc_youtube",
    sourceIds: ["source_yc_youtube"],
    title: "Common Mistakes With Vibe Coded Websites",
    excerpt:
      "Y Combinator breaks down the visual traps of no-code and AI-generated websites, from generic gradients to over-designed interaction flourishes.",
    canonicalUrl: "https://www.youtube.com/watch?v=DNSXlBmukck",
    contentType: "video",
    publishedAt: new Date("2026-03-06T15:00:31.000Z"),
    ingestedAt: new Date("2026-03-07T13:00:00.000Z"),
    fingerprint: "fp_yc_1",
    authorName: "Y Combinator",
    thumbnailUrl: "https://i.ytimg.com/vi/DNSXlBmukck/hqdefault.jpg",
    mediaLabel: "07:44",
    tagIds: ["tag_aiux", "tag_pattern"],
  },
  {
    id: "item_diveclub_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    primarySourceId: "source_diveclub_youtube",
    sourceIds: ["source_diveclub_youtube"],
    title: "hey, cool hover state!",
    excerpt:
      "A short-form design critique from Dive Club focused on craft details, portfolio polish, and micro-interaction taste.",
    canonicalUrl: "https://www.youtube.com/shorts/gbS0KF6eEgs",
    contentType: "video",
    publishedAt: new Date("2026-03-06T14:16:13.000Z"),
    ingestedAt: new Date("2026-03-07T13:00:00.000Z"),
    fingerprint: "fp_diveclub_1",
    authorName: "Dive Club",
    thumbnailUrl: "https://i.ytimg.com/vi/gbS0KF6eEgs/hqdefault.jpg",
    mediaLabel: "00:31",
    tagIds: ["tag_aiux", "tag_pattern"],
  },
  {
    id: "item_framer_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    primarySourceId: "source_framer_youtube",
    sourceIds: ["source_framer_youtube"],
    title: "Ship websites with enterprise needs, at startup speeds",
    excerpt:
      "Framer showcases enterprise-scale publishing, localization, and multi-domain workflows without losing the speed of a startup web team.",
    canonicalUrl: "https://www.youtube.com/watch?v=ji8VijpvrBA",
    contentType: "video",
    publishedAt: new Date("2026-03-05T17:04:53.000Z"),
    ingestedAt: new Date("2026-03-07T13:00:00.000Z"),
    fingerprint: "fp_framer_1",
    authorName: "Framer",
    thumbnailUrl: "https://i.ytimg.com/vi/ji8VijpvrBA/hqdefault.jpg",
    mediaLabel: "01:26",
    tagIds: ["tag_aiux", "tag_feature", "tag_pattern"],
  },
  {
    id: "item_alanchen_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    primarySourceId: "source_alanchen_youtube",
    sourceIds: ["source_alanchen_youtube"],
    title: "2027年AGI降临？前OpenAI核心成员的165页绝密报告",
    excerpt:
      "Alan Chen covers a former OpenAI team member's AGI outlook and the business implications behind large-scale AI bets.",
    canonicalUrl: "https://www.youtube.com/watch?v=EgZ-lURsrsQ",
    contentType: "video",
    publishedAt: new Date("2026-03-05T22:27:08.000Z"),
    ingestedAt: new Date("2026-03-07T13:00:00.000Z"),
    fingerprint: "fp_alanchen_1",
    authorName: "Alan Chen",
    thumbnailUrl: "https://i.ytimg.com/vi/EgZ-lURsrsQ/hqdefault.jpg",
    mediaLabel: "18:42",
    tagIds: ["tag_aiux"],
  },
  {
    id: "item_skateiq_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: null,
    primarySourceId: "source_skateiq_youtube",
    sourceIds: ["source_skateiq_youtube"],
    title: "The easiest rotation to learn",
    excerpt:
      "A compact tutorial short from SkateIQ. This is included as an intentionally off-profile source to test how mixed-interest feeds read in the new layout.",
    canonicalUrl: "https://www.youtube.com/shorts/Aua-Xr1UsA4",
    contentType: "video",
    publishedAt: new Date("2026-03-07T04:46:15.000Z"),
    ingestedAt: new Date("2026-03-07T13:00:00.000Z"),
    fingerprint: "fp_skateiq_1",
    authorName: "SkateIQ",
    thumbnailUrl: "https://i.ytimg.com/vi/Aua-Xr1UsA4/hqdefault.jpg",
    mediaLabel: "00:24",
    tagIds: [],
  },
  {
    id: "item_ai_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    primarySourceId: "source_nn_group",
    sourceIds: ["source_nn_group"],
    title: "Designing for AI confidence: how to show uncertainty without losing trust",
    excerpt: "A practical look at confidence cues, escalation states, and how to keep users oriented when AI output quality varies.",
    canonicalUrl: "https://www.nngroup.com/articles/ai-confidence-patterns",
    contentType: "article",
    publishedAt: new Date("2026-03-06T06:00:00.000Z"),
    ingestedAt: new Date("2026-03-06T08:00:00.000Z"),
    fingerprint: "fp_ai_1",
    authorName: "NN/g",
    thumbnailUrl: null,
    tagIds: ["tag_aiux", "tag_pattern"],
  },
  {
    id: "item_ai_2",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_aiux",
    primarySourceId: "source_lenny",
    sourceIds: ["source_lenny"],
    title: "AI-first onboarding: teaching power users without slowing the first session",
    excerpt: "Notes from a product interview on progressive disclosure, agent handoff and high-signal starter workflows.",
    canonicalUrl: "https://youtube.com/watch?v=signal-ai-onboarding",
    contentType: "video",
    publishedAt: new Date("2026-03-05T17:30:00.000Z"),
    ingestedAt: new Date("2026-03-06T08:15:00.000Z"),
    fingerprint: "fp_ai_2",
    authorName: "Lenny's Podcast",
    thumbnailUrl: null,
    mediaLabel: "06:11",
    tagIds: ["tag_aiux"],
  },
  {
    id: "item_tp_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_truckerpath",
    primarySourceId: "source_truckerpath_blog",
    sourceIds: ["source_truckerpath_blog"],
    title: "Trucker Path refreshes route planning dashboard for fleet dispatchers",
    excerpt: "A product update focused on route context panels, lane filters and more visible stop intelligence.",
    canonicalUrl: "https://truckerpath.com/blog/route-planning-dashboard-refresh",
    contentType: "update",
    publishedAt: new Date("2026-03-06T04:45:00.000Z"),
    ingestedAt: new Date("2026-03-06T08:22:00.000Z"),
    fingerprint: "fp_tp_1",
    authorName: "Trucker Path",
    thumbnailUrl: null,
    tagIds: ["tag_truckerpath", "tag_competitor", "tag_navigation", "tag_feature"],
  },
  {
    id: "item_tp_2",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_truckerpath",
    primarySourceId: "source_truckerpath_blog",
    sourceIds: ["source_truckerpath_blog"],
    title: "Trucker Path announces partner network expansion for fuel savings",
    excerpt: "The move signals a broader platform story around trip planning, partnerships and lane economics.",
    canonicalUrl: "https://truckerpath.com/blog/fuel-partner-network-expansion",
    contentType: "article",
    publishedAt: new Date("2026-03-05T11:00:00.000Z"),
    ingestedAt: new Date("2026-03-06T08:22:00.000Z"),
    fingerprint: "fp_tp_2",
    authorName: "Trucker Path",
    thumbnailUrl: null,
    tagIds: ["tag_truckerpath", "tag_competitor", "tag_partnership"],
  },
  {
    id: "item_al_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_ailoadboard",
    primarySourceId: "source_ailoadboard_x",
    sourceIds: ["source_ailoadboard_x"],
    title: "AI Loadboard teases dynamic lane pricing controls on X",
    excerpt: "The post hints at broker-facing pricing levers and faster feedback loops in the loadboard workflow.",
    canonicalUrl: "https://x.com/AILoadboard/status/1001",
    contentType: "post",
    publishedAt: new Date("2026-03-06T02:40:00.000Z"),
    ingestedAt: new Date("2026-03-06T07:40:00.000Z"),
    fingerprint: "fp_al_1",
    authorName: "AI Loadboard",
    thumbnailUrl: null,
    tagIds: ["tag_ailoadboard", "tag_competitor", "tag_loadboard", "tag_pricing"],
  },
  {
    id: "item_nav_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: "entity_navpro",
    primarySourceId: "source_navpro_updates",
    sourceIds: ["source_navpro_updates"],
    title: "NavPro web adds map-side trip edit drawer with persistent route context",
    excerpt: "A web release aimed at reducing full-page jumps when refining a route mid-planning session.",
    canonicalUrl: "https://example.com/navpro/release/trip-edit-drawer",
    contentType: "update",
    publishedAt: new Date("2026-03-06T01:00:00.000Z"),
    ingestedAt: new Date("2026-03-06T08:05:00.000Z"),
    fingerprint: "fp_nav_1",
    authorName: "NavPro",
    thumbnailUrl: null,
    tagIds: ["tag_navpro", "tag_navigation", "tag_feature"],
  },
  {
    id: "item_industry_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: null,
    primarySourceId: "source_ailoadboard_x",
    sourceIds: ["source_ailoadboard_x"],
    title: "Loadboard operators are shifting pricing communication into live surfaces",
    excerpt: "Across web apps and social previews, pricing updates are moving closer to dispatch workflows rather than buried in docs.",
    canonicalUrl: "https://x.com/AILoadboard/status/1002",
    contentType: "post",
    publishedAt: new Date("2026-03-04T20:20:00.000Z"),
    ingestedAt: new Date("2026-03-06T07:40:00.000Z"),
    fingerprint: "fp_industry_1",
    authorName: "AI Loadboard",
    thumbnailUrl: null,
    tagIds: ["tag_loadboard", "tag_pricing"],
  },
  {
    id: "item_gallery_1",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: null,
    primarySourceId: "source_saaslandingpage_gallery",
    sourceIds: ["source_saaslandingpage_gallery"],
    title: "Interfere",
    excerpt:
      "A high-contrast engineering landing page with crisp typography, restrained gradients, and a long-form product narrative.",
    canonicalUrl: "https://saaslandingpage.com/interfere/",
    contentType: "article",
    publishedAt: new Date("2026-03-10T11:55:31.000Z"),
    ingestedAt: new Date("2026-03-10T12:00:00.000Z"),
    fingerprint: "fp_gallery_interfere",
    authorName: null,
    thumbnailUrl: "https://saaslandingpage.com/wp-content/uploads/2026/03/interfere.png",
    tagIds: ["tag_website_inspiration"],
  },
  {
    id: "item_gallery_2",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: null,
    primarySourceId: "source_onepagelove_gallery",
    sourceIds: ["source_onepagelove_gallery"],
    title: "Website Inspiration: Killian Herzer",
    excerpt:
      "A futuristic CV-style portfolio with three-dimensional transitions, dense motion, and an editorial one-page structure.",
    canonicalUrl: "https://onepagelove.com/killian-herzer",
    contentType: "article",
    publishedAt: new Date("2026-03-10T14:46:17.000Z"),
    ingestedAt: new Date("2026-03-10T14:50:00.000Z"),
    fingerprint: "fp_gallery_killian_herzer",
    authorName: "Rob Hope @robhope",
    thumbnailUrl:
      "https://assets.onepagelove.com/cdn-cgi/image/width=1200,height=1200,fit=cover,gravity=top,format=jpg,quality=85/wp-content/uploads/2026/03/opl-master-7.jpg",
    tagIds: ["tag_website_inspiration"],
  },
  {
    id: "item_gallery_3",
    workspaceId: DEMO_WORKSPACE_ID,
    entityId: null,
    primarySourceId: "source_a1_gallery",
    sourceIds: ["source_a1_gallery"],
    title: "Sendr",
    excerpt: "A1 Gallery feature with a bold courier-style product story and refined commerce art direction.",
    canonicalUrl: "https://www.a1.gallery/website/sendr",
    contentType: "article",
    publishedAt: new Date("2026-03-10T12:30:00.000Z"),
    ingestedAt: new Date("2026-03-10T12:30:00.000Z"),
    fingerprint: "fp_gallery_sendr",
    authorName: null,
    thumbnailUrl: "https://pub-b5b31c092f684301a4595f6ea937a598.r2.dev/websites/sendr/desktop",
    tagIds: ["tag_website_inspiration"],
  },
];
